name = "Client"
author = "Amber"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff433c7916a7b5ed3d1c0e76e933dbe24c7fe9b93572f77e2a58db124db78f9c"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
