name = "Client"
author = "Amber"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98db8ff506f861a880b8e7c23eb210c4646f79ad11155f2dd67a52f95be7a117"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
