name = "Client"
author = "Amber"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3fee514e5f4d0af12e5f6babe4e2048ee1ae8944213200e0e93d75fd87e5d101"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
