name = "Server"
author = "Amber"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "312d69f30785934ef36234a36ceeb5937b15e7bf7ab1c5d8d732c37fcf3e363e"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
