name = "Server"
author = "Amber"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a7bb418e492aacbc177a3acc7d637cc1dafef3c4e77503c76b939f3ba110239"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
