name = "Server"
author = "Amber"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "672ab675d68172bf698ec25a962e9fb4a44c47b80ba92163fd2139c979f1f1f2"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
